- name: "HTH | Just | Set version executable path"
  ansible.builtin.set_fact:
    just_version_executable_path: "{{ just_default_path }}/{{ just.default }}/just"

- name: "HTH | Just | Stat version executable"
  ansible.builtin.stat:
    path:  "{{ just_version_executable_path }}"
  register: just_default_version_executable

- name: "HTH | Just | Fail on version executable not existing"
  ansible.builtin.fail:
    msg: "Executable for version {{ just.default }} was not found!"
  when: 
    - not just_default_version_executable.stat.exists

- name: "HTH | Just | Set as global version"
  community.general.alternatives:
    name: just
    link: /usr/bin/just
    path: "{{ just_version_executable_path }}"
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
