- name: Download and unarchive Just version
  block:

  - name: Ensure 'just_install_path' directory
    ansible.builtin.file:
      path: "{{ just_install_path }}"
      state: directory
      modification_time: preserve
      access_time: preserve
      owner: "root"
      group: "root"
      mode: 0755


  - name: Set install location
    ansible.builtin.set_fact:
      just_version_install_path: "{{ just_install_path }}/{{ version }}"


  - name: Stat version directory
    ansible.builtin.stat:
      path:  "{{ just_version_install_path }}"
    register: version_dir


  - name: Set archive name
    ansible.builtin.set_fact:
      just_archive_name: "just-{{ version }}.tar.gz"


  - name: Download version archive
    ansible.builtin.get_url:
      url: "https://github.com/casey/just/releases/download/{{ version }}/just-{{ version }}-x86_64-unknown-linux-musl.tar.gz"
      dest: "/tmp/{{ just_archive_name }}"
    register: archive_download_state
    when: not version_dir.stat.exists


  - name: Extract archive
    ansible.builtin.unarchive:
      remote_src: yes
      src: "/tmp/{{ just_archive_name }}"
      dest: "{{ just_version_install_path }}"
      extra_opts: [--strip-components=1]
      owner: "root"
      group: "root"
      mode: 0755
    register: unarchive_state
    when: not version_dir.stat.exists



  always:

    - name: Cleanup temporary directory
      ansible.builtin.file:
        path: "/tmp/{{ just_archive_name }}"
        state: absent
