- name: Assert necessary variables and environment for Just installation
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Download versions
  ansible.builtin.include_tasks: download.yml
  loop: "{{ just.versions }}"
  loop_control:
    loop_var: version
  when: just.versions | length > 0


- name: Trim undefined versions
  ansible.builtin.include_tasks: trim.yml
  when: just.trim


- name: Link default version
  ansible.builtin.include_tasks: default.yml
  when: 
    - just.default | length > 0 
