- name: "HTH | Just | Assert input variables"
  ansible.utils.validate:
    data: "{{ just }}"
    criteria: "{{ lookup('file', 'assertions/criteria/just.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost

- name: "HTH | Just | Set default executable symlink path"
  ansible.builtin.set_fact:
    just_default_executable_symlink_destination: "/usr/bin/just"

- name: "HTH | Just | Download versions"
  ansible.builtin.include_tasks: download.yml
  loop: "{{ just.versions }}"
  loop_control:
    loop_var: version
  when:
    - just.versions | length > 0
    - just.remove is undefined or not just.remove

- name: "HTH | Just | Trim undefined versions"
  ansible.builtin.include_tasks: trim.yml
  when:
    - just.trim
    - just.remove is undefined or not just.remove

- name: "HTH | Just | Link default version"
  ansible.builtin.include_tasks: default.yml
  when:
    - just.default | length > 0
    - just.remove is undefined or not just.remove

- name: "HTH | Just | Remove installation"
  ansible.builtin.include_tasks: remove.yml
  when:
    - just.remove is defined
    - just.remove

- name: "HTH | Just | Generate auto complete for 'bash'"
  ansible.builtin.include_tasks: completion.yml
  loop: "{{ just.completions.bash }}"
  loop_control:
    loop_var: user
  vars:
    shell_name: "bash"
    shell_completion_dir: "{{ just_default_bash_completion_path }}"
  when:
    - just.remove is undefined or not just.remove
    - just.completions is defined
    - just.completions.bash is defined

- name: "HTH | Just | Generate auto complete for 'zsh'"
  ansible.builtin.include_tasks: completion.yml
  loop: "{{ just.completions.zsh }}"
  loop_control:
    loop_var: user
  vars:
    shell_name: "zsh"
    shell_completion_dir: "{{ just_default_zsh_completion_path }}"
  when:
    - just.remove is undefined or not just.remove
    - just.completions is defined
    - just.completions.zsh is defined

- name: "HTH | Just | Generate auto complete for 'ohmyzsh'"
  ansible.builtin.include_tasks: completion.yml
  loop: "{{ just.completions.ohmyzsh }}"
  loop_control:
    loop_var: user
  vars:
    shell_name: "zsh"
    shell_completion_dir: "{{ just_default_ohmyzsh_completion_path }}"
  when:
    - just.remove is undefined or not just.remove
    - just.completions is defined
    - just.completions.ohmyzsh is defined

- name: "HTH | Just | Generate auto complete for 'fish'"
  ansible.builtin.include_tasks: completion.yml
  loop: "{{ just.completions.bash }}"
  loop_control:
    loop_var: user
  vars:
    shell_name: "fish"
    shell_completion_dir: "{{ just_default_fish_completion_path }}"
  when:
    - just.remove is undefined or not just.remove
    - just.completions is defined
    - just.completions.fish is defined
